package ASE_Project;

import simView.*;

import java.awt.*;
import java.io.*;

import DEVSJAVALab.carGenr;
import genDevs.modeling.*;
import genDevs.simulation.*;
import GenCol.*;


public class CarRentalSystem extends ViewableDigraph{
	
	public CarRentalSystem() {this("CarRentalSystem");}
	
	public CarRentalSystem(String name) {
		super(name);
		CarRentalSystemConstruct();
	}
	
	public void CarRentalSystemConstruct() {
		this.addOutport("out0");
		this.addOutport("out1");
		this.addOutport("out2");
		
		ViewableAtomic cust_genr = new customerGenerator("customerGenerator",5);
		ViewableAtomic paper_work = new PaperWork("PaperWork");
		ViewableAtomic economy_car = new Economy("Economy");
		
		add(cust_genr);
		add(paper_work);
		add(economy_car);
		
		addCoupling(cust_genr,"cust_gen",paper_work,"Cust_In");
		addCoupling(paper_work, "CheckedIn_0", economy_car, "economyIn");
		addCoupling(economy_car, "economyOut", this, "out0");
		addCoupling(paper_work, "CheckedIn_1", this, "out1");
		addCoupling(paper_work, "CheckedIn_2", this, "out2");
	}

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(734, 402);
        if((ViewableComponent)withName("PaperWork")!=null)
             ((ViewableComponent)withName("PaperWork")).setPreferredLocation(new Point(211, 133));
        if((ViewableComponent)withName("customerGenerator")!=null)
             ((ViewableComponent)withName("customerGenerator")).setPreferredLocation(new Point(19, 127));
        if((ViewableComponent)withName("Economy")!=null)
             ((ViewableComponent)withName("Economy")).setPreferredLocation(new Point(358, 28));
    }
}
